<a href="https://colab.research.google.com/github/rheona2000/python-numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
array1= np.array([10,20,30])
print(array1)

array2=np.array([2,3,'r',"rheona"])
print(array2)

[10 20 30]
['2' '3' 'r' 'rheona']


In [ ]:
temp =np.array([5,6,7,8,"rio"],dtype=str)
print(temp)

['5' '6' '7' '8' 'rio']


In [ ]:
array3 = np.array([[2,3,4],[7,5,6],[7,8,9]])
print(array3)

[[2 3 4]
 [7 5 6]
 [7 8 9]]


In [ ]:
array3.ndim

2

In [ ]:
array1.shape

(3,)

In [ ]:
array3.shape

(3, 3)

In [ ]:
print(array1.size)

3


In [ ]:
print(array1.dtype)

int64


In [ ]:
print(array1.itemsize)

8


In [ ]:
array5=np.ones((3,4))
print(array5)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
array6=np.arange(10)
print(array6)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
array7=np.arange(-2,24,4)
print(array7)
print(array7[1])

[-2  2  6 10 14 18 22]
2


In [ ]:
print(array7[2])

6


In [ ]:
print(array3)
print(array3[2,2])

[[2 3 4]
 [7 5 6]
 [7 8 9]]
9


In [ ]:
array8=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12,]])
print(array8)
print(array8[0:3,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 3  7 11]


In [ ]:
import numpy as np

a1=np.array([1,2,3,4,5])
print(a1.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [ ]:
x=np.empty([3,2], dtype=int)
print(x)

[[94219356266784              0]
 [             0              0]
 [             0              0]]


In [ ]:
x=np.linspace(10,20,5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [ ]:
a=np.logspace(1,10,num=10,base=2)
print(a)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [ ]:
x=np.array([[1,2],[3,4],[5,6]])
p=x[[0,1,2],[0,1,0]]
print(p)

[1 4 5]


In [ ]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
rows=np.array([[0,0],[3,3]])
cols=np.array([[0,2],[0,2]])
y=x[rows,cols]
print(y)

[[ 0  2]
 [ 9 11]]


flat

In [ ]:
import numpy as np
a=np.arange(10).reshape(2,5)
print(a.flat[1])

1


swapaxes

In [ ]:
a=np.arange(8).reshape(2,4)
print(a)
print(a.swapaxes(1,0))

[[0 1 2 3]
 [4 5 6 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


flatten

In [ ]:
import numpy as np
a=np.arange(10).reshape(2,5)
print(a)
print(a.flatten())

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


ravel

In [ ]:
import numpy as np
a=np.arange(10).reshape(2,5)
print(a)
print(a.ravel())

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


Broadcast

In [ ]:
a=np.arange(4).reshape(1,4)
print(a)
print("\n")
print(np.broadcast_to(a,(4,4)))

[[0 1 2 3]]


[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


Stack

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.stack((a,b),1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

split operation

In [ ]:
a=np.arange(16).reshape(4,4)
print(a)
b=np.split(a,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


string Functions, bitwise Operators